plugins {
    id "com.android.application"
}

android {
    namespace "cc.onedesk.mobile"
    compileSdk 36

    defaultConfig {
        applicationId "cc.onedesk.mobile"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "0.1.0"
    }

    sourceSets {
        main {
            assets.srcDirs += file("../../../../frontends/mobile/dist")
        }
    }
}
